### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [jxareas/Xpensor#31]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
Glad to see you're self-assigned this, thanks! Do you have an ETA when a release-signed APK might be available, @jxareas? No pressure, just asking for orientation.

**Comment by jxareas** [comment]
Greetings @IzzySoft.

I apologize for not providing an ETA. Signed apk is now available under [`xpensor.apk`](https://github.com/jxareas/Xpensor/releases/download/v0.1.0-alpha/xpensor.apk) in the `v0.1.0-alpha01` [release section](https://github.com/jxareas/Xpensor/releases/tag/v0.1.0-alpha).

Running `apksigner verify --verbose --print-certs-pem xpensor-release.apk` should output `DN: C=CR, L=Costa Rica, CN=Jon Areas` in the certificate DN as opposed to debug certificate's `DN: C=US, O=Android, CN=Android Debug`.

**Comment by IzzySoft** [comment]
Thanks! But you decreased `versionCode` there (the debug has `versionCode:2`, the new one has `1`):

old debug APK:

    package: name='com.jxareas.xpensor' versionCode='2' versionName='0.1.0-alpha01'

New release APK:

    package: name='com.jxareas.xpensor' versionCode='1' versionName='1.0'

That does not even match the tag/version anymore. You sure it should be this way?

**Comment by IzzySoft** [comment]
@jxareas Just a ping in case the notification got lost (some went AWOL for me, too, so the possibility exists): was the above (decreasing `versionCode` while increasing `versionName`) intended?

**Comment by IzzySoft** [comment]
@jxareas ^^ any word? Do all notifications get lost now? :thinking:

**Comment by IzzySoft** [comment]
@jxareas last ping. End of this month, remaining APKs signed with debug keys will be removed from my repo. If there's no fitting APK signed by a release key, that means the app will disappear from the repo. It can of course be re-established later, but will be gone until fixed.

**Comment by jxareas** [comment]
> versionCode='2' versionName='0.1.0-alpha01'

Hi @IzzySoft. 

That is correct. The new release-signed apk has a decreased version code with an unproperly set tag.

I will address this quickly. Thanks for letting me know.

**Comment by IzzySoft** [comment]
Hm, not sure how quick "quickly" might be, but I'm now going to remove the remainders. Folks need to uninstall and re-install anyway, so the decreased `versionCode` is no major issue for them. Will be a little confusion later should you go back from 1.x to 0.x in the `versionName`, though – but as I assume you prefer that to having your app removed entirely, I'll now replace it that way.

**Comment by jxareas** [comment]
>Thanks! But you decreased versionCode there (the debug has versionCode:2, the new one has 1):

Well, I appreciate the heads up. The new signed release apk  now has `package: name='com.jxareas.xpensor' versionCode='2' versionName='0.1.0-alpha01'` just like the former release apk.

**Comment by IzzySoft** [comment]
Thanks – and good you told me, as the expected happened:

```
$ iod repo get com.jxareas.xpensor
com.jxareas.xpensor: looking for 'https://api.github.com/repos/jxareas/Xpensor/releases'
com.jxareas.xpensor: checking tag 'v0.1.0-alpha'
com.jxareas.xpensor: returning ['0','',]
com.jxareas.xpensor: 1.0 up-to-date.
```

(the updater, going by the tag name, thinks it already has a newer version here). Going to fix that now… Done. Purged out the other one while on it, to avoid confusion. Thanks a lot, solved then \o/
